#!/usr/bin/env python3
"""Regenerate docs/development/PRODUCTION_READINESS.md from the per-file
@adai-status tags. See docs/development/guides/file-status-standard.md.

Usage:
    ./scripts/gen_status_report.py
"""
# @adai-status: beta        (validated via manual test cases this session; no formal test suite; capped by TD-043 — see TECHNICAL_DEBT.md)
# @adai-version: 0.9.0
# @adai-reviewed: 2026-09-07
from __future__ import annotations

import datetime
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_file_status import (  # noqa: E402
    REPO_ROOT, TAG_RE, MAX_HEADER_LINES, in_scope_files,
)

OUT_PATH = REPO_ROOT / "docs" / "development" / "PRODUCTION_READINESS.md"
STALE_AFTER_DAYS = 180
TD_REF_RE = re.compile(r"\bTD-\d+\b")


def component_of(path: Path) -> str:
    rel = path.relative_to(REPO_ROOT)
    return rel.parts[0]


def read_tag(path: Path) -> dict | None:
    header = "\n".join(path.read_text(errors="replace").splitlines()[:MAX_HEADER_LINES])
    m = TAG_RE.search(header)
    if not m:
        return None
    # Use the matched span's own first line, not a substring search over the whole
    # header — a file whose docstring mentions "@adai-status" (like this script and
    # check_file_status.py do) would otherwise match that line instead of the real tag.
    status_line = header[m.start():].splitlines()[0]
    td_ref = TD_REF_RE.search(status_line)
    return {
        "status": m.group("status"),
        "version": m.group("version"),
        "reviewed": m.group("reviewed"),
        "td_ref": td_ref.group(0) if td_ref else None,
    }


def main() -> int:
    files = in_scope_files()
    today = datetime.date.today()

    by_component: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    untagged: list[Path] = []
    needs_review: list[tuple[Path, dict]] = []
    experimental_or_beta: list[tuple[Path, dict]] = []

    for path in files:
        tag = read_tag(path)
        comp = component_of(path)
        if tag is None:
            untagged.append(path)
            by_component[comp]["untagged"] += 1
            continue

        by_component[comp][tag["status"]] += 1

        if tag["status"] in ("experimental", "beta"):
            experimental_or_beta.append((path, tag))

        if tag["status"] == "stable":
            try:
                reviewed = datetime.date.fromisoformat(tag["reviewed"])
                if (today - reviewed).days > STALE_AFTER_DAYS:
                    needs_review.append((path, tag))
            except ValueError:
                needs_review.append((path, tag))

    all_statuses = ["stable", "beta", "experimental", "deprecated", "legacy", "untagged"]
    total = len(files)

    lines = []
    lines.append("# Production Readiness Report")
    lines.append("")
    lines.append("**Generated by `scripts/gen_status_report.py` — do not hand-edit, "
                  "re-run the script instead.**")
    lines.append("")
    lines.append(f"Generated: {today.isoformat()} · {total} in-scope file(s) scanned.")
    lines.append("")
    lines.append("See [file-status-standard.md](guides/file-status-standard.md) for what these "
                  "statuses mean and how to update a file's tag.")
    lines.append("")

    lines.append("## Summary by component")
    lines.append("")
    header = ["Component"] + [s.capitalize() for s in all_statuses] + ["Total"]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "---|" * len(header))
    for comp in sorted(by_component):
        counts = by_component[comp]
        row = [comp] + [str(counts.get(s, 0)) for s in all_statuses]
        row.append(str(sum(counts.values())))
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    stable_total = sum(c.get("stable", 0) for c in by_component.values())
    pct = (100 * stable_total / total) if total else 0
    lines.append(f"**{stable_total}/{total} files ({pct:.0f}%) are tagged `stable`.**")
    lines.append("")

    lines.append("## Untagged files")
    lines.append("")
    if untagged:
        lines.append("These are in scope but carry no `@adai-status` tag yet:")
        lines.append("")
        for path in untagged:
            lines.append(f"- `{path.relative_to(REPO_ROOT)}`")
    else:
        lines.append("None — every in-scope file carries a tag.")
    lines.append("")

    lines.append("## Experimental / beta files")
    lines.append("")
    if experimental_or_beta:
        lines.append("| File | Status | Version | Reviewed | Debt ref |")
        lines.append("|---|---|---|---|---|")
        for path, tag in experimental_or_beta:
            lines.append(
                f"| `{path.relative_to(REPO_ROOT)}` | {tag['status']} | {tag['version']} | "
                f"{tag['reviewed']} | {tag['td_ref'] or '—'} |"
            )
    else:
        lines.append("None.")
    lines.append("")

    lines.append(f"## Stable files overdue for re-attestation (> {STALE_AFTER_DAYS} days)")
    lines.append("")
    if needs_review:
        lines.append("| File | Version | Last reviewed |")
        lines.append("|---|---|---|")
        for path, tag in needs_review:
            lines.append(f"| `{path.relative_to(REPO_ROOT)}` | {tag['version']} | {tag['reviewed']} |")
    else:
        lines.append("None.")
    lines.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
