#!/usr/bin/env python3
"""
Training Metrics Monitor - Real-time CLI dashboard for training metrics

This script polls the metrics files generated by TrainingMetricsService
and displays a live dashboard in the terminal.

Usage:
    python3 monitor_training.py [options]

Options:
    --summary-file PATH    Path to the JSON summary file (default: training_sessions/metrics_summary.json)
    --refresh-rate N       Refresh interval in seconds (default: 2)
    --format FORMAT        Display format: full, compact, minimal (default: full)
"""

import json
import time
import sys
import os
import argparse
from datetime import datetime, timedelta

def clear_screen():
    """Clear the terminal screen"""
    os.system('cls' if os.name == 'nt' else 'clear')

def format_duration(seconds):
    """Format duration in seconds to human-readable string"""
    if seconds < 60:
        return f"{seconds:.1f}s"
    elif seconds < 3600:
        minutes = seconds / 60
        return f"{minutes:.1f}m"
    else:
        hours = seconds / 3600
        return f"{hours:.2f}h"

def create_progress_bar(current, total, width=40):
    """Create a text progress bar"""
    if total == 0:
        return "[" + " " * width + "]"
    
    filled = int(width * current / total)
    bar = "=" * filled + ">" + " " * (width - filled - 1)
    percentage = 100 * current / total
    return f"[{bar}] {percentage:.1f}%"

def format_loss_trend(losses):
    """Format loss trend with simple sparkline"""
    if len(losses) < 2:
        return "N/A"
    
    recent_losses = losses[-5:]
    trend = "↓" if recent_losses[-1] < recent_losses[0] else "↑" if recent_losses[-1] > recent_losses[0] else "→"
    
    # Simple sparkline using Unicode block characters
    if len(recent_losses) >= 2:
        min_loss = min(recent_losses)
        max_loss = max(recent_losses)
        range_loss = max_loss - min_loss
        
        if range_loss > 0:
            sparkline = ""
            chars = " ▁▂▃▄▅▆▇█"
            for loss in recent_losses:
                idx = int((loss - min_loss) / range_loss * (len(chars) - 1))
                sparkline += chars[idx]
        else:
            sparkline = "▄" * len(recent_losses)
    else:
        sparkline = ""
    
    return f"{trend} {sparkline}"

def display_full_dashboard(data):
    """Display full dashboard with all metrics"""
    print("=" * 80)
    print(f"{'TRAINING METRICS DASHBOARD':^80}")
    print("=" * 80)
    print()
    
    # Session info
    print(f"Session ID: {data.get('session_id', 'N/A')}")
    print(f"Status: {'TRAINING' if data.get('is_training', False) else 'IDLE'}")
    print(f"Timestamp: {data.get('timestamp', 'N/A')}")
    print()
    
    # Progress
    current_epoch = data.get('current_epoch', 0)
    total_epochs = data.get('total_epochs', 0)
    current_sample = data.get('current_sample', 0)
    total_samples = data.get('total_samples', 0)
    
    print(f"Epoch Progress: {current_epoch}/{total_epochs}")
    if total_epochs > 0:
        print(f"  {create_progress_bar(current_epoch, total_epochs)}")
    print()
    
    print(f"Sample Progress: {current_sample}/{total_samples}")
    if total_samples > 0:
        print(f"  {create_progress_bar(current_sample, total_samples)}")
    print()
    
    # Current metrics
    print("-" * 80)
    print(f"{'CURRENT METRICS':^80}")
    print("-" * 80)
    
    current_loss = data.get('current_loss', 0)
    running_loss = data.get('running_loss', 0)
    val_loss = data.get('current_validation_loss', 0)
    lr = data.get('current_learning_rate', 0)
    grad_norm = data.get('current_gradient_norm', 0)
    perplexity = data.get('current_perplexity', 0)
    
    print(f"Loss:            {current_loss:.6f}  (running avg: {running_loss:.6f})")
    print(f"Validation Loss: {val_loss:.6f}")
    print(f"Perplexity:      {perplexity:.4f}")
    print(f"Learning Rate:   {lr:.6f}")
    print(f"Gradient Norm:   {grad_norm:.6f}")
    print()
    
    # Best metrics
    best_loss = data.get('best_validation_loss', float('inf'))
    best_epoch = data.get('best_epoch', -1)
    if best_epoch >= 0:
        print(f"Best Val Loss:   {best_loss:.6f}  (epoch {best_epoch})")
        print()
    
    # Throughput
    print("-" * 80)
    print(f"{'PERFORMANCE':^80}")
    print("-" * 80)
    
    samples_trained = data.get('total_samples_trained', 0)
    training_time = data.get('total_training_time_seconds', 0)
    throughput = data.get('samples_per_second', 0)
    eta = data.get('estimated_time_remaining_seconds', 0)
    
    print(f"Samples Trained: {samples_trained}")
    print(f"Training Time:   {format_duration(training_time)}")
    print(f"Throughput:      {throughput:.2f} samples/sec")
    if eta > 0:
        print(f"ETA:             {format_duration(eta)}")
    print()
    
    # Epoch history
    epoch_losses = data.get('epoch_losses', [])
    if epoch_losses:
        print("-" * 80)
        print(f"{'EPOCH HISTORY':^80}")
        print("-" * 80)
        
        epoch_val_losses = data.get('epoch_validation_losses', [])
        epoch_lrs = data.get('epoch_learning_rates', [])
        epoch_durations = data.get('epoch_durations', [])
        
        print(f"{'Ep':>4} {'Loss':>10} {'Val Loss':>10} {'LR':>10} {'Duration':>10} {'Trend':>10}")
        print("-" * 80)
        
        for i in range(min(10, len(epoch_losses))):  # Show last 10 epochs
            loss = epoch_losses[i]
            val_loss = epoch_val_losses[i] if i < len(epoch_val_losses) else 0
            lr = epoch_lrs[i] if i < len(epoch_lrs) else 0
            duration = epoch_durations[i] if i < len(epoch_durations) else 0
            
            trend = format_loss_trend(epoch_losses[:i+1])
            
            print(f"{i:4} {loss:10.6f} {val_loss:10.6f} {lr:10.6f} {format_duration(duration):>10} {trend:>10}")
        
        if len(epoch_losses) > 10:
            print(f"\n... and {len(epoch_losses) - 10} more epochs")

def display_compact_dashboard(data):
    """Display compact dashboard"""
    print("=" * 60)
    print(f"{'TRAINING METRICS':^60}")
    print("=" * 60)
    
    status = "TRAINING" if data.get('is_training', False) else "IDLE"
    epoch = f"{data.get('current_epoch', 0)}/{data.get('total_epochs', 0)}"
    sample = f"{data.get('current_sample', 0)}/{data.get('total_samples', 0)}"
    
    print(f"Session: {data.get('session_id', 'N/A')} | Status: {status}")
    print(f"Epoch: {epoch} | Sample: {sample}")
    print()
    
    loss = data.get('current_loss', 0)
    val_loss = data.get('current_validation_loss', 0)
    ppl = data.get('current_perplexity', 0)
    throughput = data.get('samples_per_second', 0)
    eta = data.get('estimated_time_remaining_seconds', 0)
    
    print(f"Loss: {loss:.4f} | Val: {val_loss:.4f} | PPL: {ppl:.2f}")
    print(f"Speed: {throughput:.1f} smp/s | ETA: {format_duration(eta)}")
    
    epoch_losses = data.get('epoch_losses', [])
    if epoch_losses:
        trend = format_loss_trend(epoch_losses)
        print(f"Trend: {trend}")

def display_minimal_dashboard(data):
    """Display minimal dashboard (one line)"""
    session = data.get('session_id', 'N/A')
    epoch = f"{data.get('current_epoch', 0)}/{data.get('total_epochs', 0)}"
    loss = data.get('current_loss', 0)
    val_loss = data.get('current_validation_loss', 0)
    throughput = data.get('samples_per_second', 0)
    
    print(f"Session {session} | Epoch {epoch} | Loss: {loss:.4f} | Val: {val_loss:.4f} | {throughput:.1f} smp/s")

def monitor_training(summary_file, refresh_rate, display_format):
    """Main monitoring loop"""
    try:
        while True:
            try:
                # Read metrics file
                with open(summary_file, 'r') as f:
                    data = json.load(f)
                
                # Clear and display
                clear_screen()
                
                if display_format == 'full':
                    display_full_dashboard(data)
                elif display_format == 'compact':
                    display_compact_dashboard(data)
                else:  # minimal
                    display_minimal_dashboard(data)
                
                print()
                print(f"Refreshing every {refresh_rate}s... (Ctrl+C to quit)")
                
            except FileNotFoundError:
                clear_screen()
                print(f"Waiting for metrics file: {summary_file}")
                print("(Training may not have started yet)")
            except json.JSONDecodeError:
                clear_screen()
                print("Error: Invalid JSON in metrics file")
                print("(File may be being written)")
            except Exception as e:
                clear_screen()
                print(f"Error reading metrics: {e}")
            
            # Wait before next refresh
            time.sleep(refresh_rate)
            
    except KeyboardInterrupt:
        print("\n\nMonitoring stopped.")
        sys.exit(0)

def main():
    parser = argparse.ArgumentParser(
        description='Real-time training metrics monitor',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        '--summary-file',
        default='training_sessions/metrics_summary.json',
        help='Path to metrics summary file (default: training_sessions/metrics_summary.json)'
    )
    
    parser.add_argument(
        '--refresh-rate',
        type=float,
        default=2.0,
        help='Refresh interval in seconds (default: 2.0)'
    )
    
    parser.add_argument(
        '--format',
        choices=['full', 'compact', 'minimal'],
        default='full',
        help='Display format (default: full)'
    )
    
    args = parser.parse_args()
    
    print(f"Monitoring: {args.summary_file}")
    print(f"Format: {args.format}")
    print(f"Refresh rate: {args.refresh_rate}s")
    print()
    time.sleep(2)
    
    monitor_training(args.summary_file, args.refresh_rate, args.format)

if __name__ == '__main__':
    main()
